### ISSUE TITLE
Unable to plot multicolor, 3 Series Chart from JSON

### ISSUE THREAD

**Issue by sakthi** [blacklabel/multicolor_series#25]
Hi Team,
I managed to plot a multicolor_series chart using 3 series of static values in which one line will vary on the color based on the value of another one series (great than the series point value then green else red). 

Please find the fiddle link is "http://jsfiddle.net/mailsakthi/1rv5jr65/3/". I tried the same concept to fetch data from MSSQL server and convert it as JSON and then use it to plot the chart, but the chart is not rendering.

I have generated a Json output as: 
[
{
"name":"month",
"data":["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar"]
},

{
"name":"Prev Year",
"type":"coloredline",
"legendColor":"grey",
"data":["y: 140, color: 'grey', segmentColor: 'grey'", 	"y: 154, color: 'grey', segmentColor: 'grey'",
	"y: 138, color: 'grey', segmentColor: 'grey'", 	"y: 173, color: 'grey', segmentColor: 'grey'",
	"y: 144, color: 'grey', segmentColor: 'grey'",	"y: 148, color: 'grey', segmentColor: 'grey'",
	"y: 168, color: 'grey', segmentColor: 'grey'","y: 130, color: 'grey', segmentColor: 'grey'",
	"y: 143, color: 'grey', segmentColor: 'grey'","y: 137, color: 'grey', segmentColor: 'grey'",
	"y: 171, color: 'grey', segmentColor: 'grey'","y: 125, color: 'grey', segmentColor: 'grey'"]
}
]

I am attaching the sample sql data set in the excel file "data.xlsx", the data fetching php "json_test.php" and the HTML file "cline_test.html" for your perusal. Also let me know if there is any alternative way to represent the values of "color: " and "segmentColor: " option with the series: [ ].

[data.zip](https://github.com/blacklabel/multicolor_series/files/1128922/data.zip)

**Comment by pawelfus** [comment]
Hi @sakthi 

Thanks for reporting this issue, but it's not related to multicolor series, simply compare your data and the one that works:

`"y: 171, color: 'grey', segmentColor: 'grey'","y: 125, color: 'grey', segmentColor: 'grey'"`
vs
`{ y: 4.2, color: 'red', segmentColor: 'red' }`

As you can see, you one point is a string, while should be JS object. I suggest to first try rendering any series (e.g. line), then rendering multicolor series type.

Regarding:
>  Also let me know if there is any alternative way to represent the values of "color: " and "segmentColor: " option with the series: [ ].

Actually, you can render blue and grey series as standard line series. For a multicolor series, this is necessary to define color for line and marker for each point.

**Comment by sakthi** [comment]
Thanks you for your reply.  I tried and successfully rendered a normal Line and Bar chart from the mssql. Then I tried to render the multicolor_series,referring to your reply I changed the json output to : 
[
{"name":"month","data":["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar",null]},{"name":"Actual",
 "data":["{y:179, segmentColor : 'green'}","{y:130, segmentColor : 'rba(128,128,128,0)'}",
             "{y:170, segmentColor : 'rba(128,128,128,0)'}","{y:190, segmentColor : 'green'}",
             "{y:137, segmentColor : 'rba(128,128,128,0)'}","{y:148, segmentColor : 'rba(128,128,128,0)'}"
           ]
}
]
----------
But I am getting only a blank chart and its not rendering. I am attaching the  data.php file where I generate the JSON and the multicolor.html file I used to render the Chart from the json object and the chart generated image file and also the JSON image file.

I noticed from the generated JSON, if I remove the double_quotes symbol("} and add and single_quotes(') to the name : 'Actual' and place that data to the series : [ ] the chart is delivery but the marker color is not taking the segment color.

Kindly request you to help me out in sorting the issue.

Thank you.
![json_output](https://user-images.githubusercontent.com/214158/27959384-d4d860f2-6344-11e7-87b8-579844f37bcb.png)
![renedered_chart_image](https://user-images.githubusercontent.com/214158/27959383-d4d7621a-6344-11e7-9107-e63502ce29da.png)
[multicolor-html_data-php.zip](https://github.com/blacklabel/multicolor_series/files/1131069/multicolor-html_data-php.zip)

**Comment by pawelfus** [comment]
Hi,

Your data format is still wrong:
```
[
  {
"name":"month",
"data":["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar",null]},{"name":"Actual",

"data":[
"{y:179,
segmentColor : 'green'}",
"{y:130,
segmentColor : 'rba(128,128,128,0)'}",
"{y:170,
segmentColor : 'rba(128,128,128,0)'}",
"{y:190,
segmentColor : 'green'}",
"{y:137,
segmentColor : 'rba(128,128,128,0)'}",
"{y:148,
segmentColor : 'rba(128,128,128,0)'}"
      ]
   }
]
```

You still have double quotes around the points, which should be objects, compare with proper format:

```
[
  {
"name":"month",
"data":["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar",null]},{"name":"Actual",

"data":[
{"y":179,
"segmentColor" : "green"},
{"y":130,
"segmentColor" : "rba(128,128,128,0)"},
{"y":170,
"segmentColor" : "rba(128,128,128,0)"},
{"y":190,
"segmentColor" : "green"},
{"y":137,
"segmentColor" : "rba(128,128,128,0)"},
{"y":148,
"segmentColor" : "rba(128,128,128,0)"}
      ]
   }
]
```

I think this SO question should help you: https://stackoverflow.com/questions/15618873/how-to-send-an-array-of-objects-in-json-format-from-php

**Comment by sakthi** [comment]
Hi Pawel,

Thanks for your input and help. I have done it and the chart is rendering
as expected. Thank you soo very much for your support. Please find the
output.

[image: Inline image 1]
Regards,
Sakthi

**Comment by pawelfus** [comment]
Great to hear that! :)

**Comment by sakthi** [comment]
Hi Pawel,

Hope this mail finds you well,

Stackoverflow Question Link:
https://stackoverflow.com/questions/46242685/typeerror-pointspointslength-1-is-undefined-while-using-multicolor-series

I am facing a problem while using multicolor.js, Series of Lines in the
Chart is not getting plotted unless one series (Previous Year)is disabled
on the chart output.

In the New Chart Loaded image you can see the loaded chart. Now when I
disable a series the other series is plotted see the image in the link
below,

I noticed when the problem occurs I see an error "TypeError:
points[(pointsLength - 1)] is undefined" while using multicolor_series.js
in the console log.

I have attached my "ecmhtb.php" the chart rendering file and "ed.php" where
the data is prepared to convert it as JSON. Also I have attached the Data
Table which is used to fetch the data from SQL and also the processed out
of SQL Data for JSON conversion as excel files.

The above mentioned issue comes in few set of data and other are working as
expected. I have updated all the required files in google drive for
inspection the link to the files
https://drive.google.com/drive/folders/0B7s2Ef_izL9EN0gtd0JoNVVhMmM
<https://drive.google.com/drive/folders/0B7s2Ef_izL9EN0gtd0JoNVVhMmM?usp=sharing>

I kindly request to help me in solving the issue. Please let me know if I
can be of any further information.

Regards,

Sakthi

**Comment by pawelfus** [comment]
Hi @sakthi 

Could you recreate issue in jsFiddle? We will take a look, thanks!

**Comment by sakthi** [comment]
I am creating the JS Fiddle, will inform you asap. thank you for the reply

**Comment by sakthi** [comment]
Hi Pawel,

My apologies for the delay in reply. i had a tough time recreating the
error in fiddle and finally was able to generate the error. Please find the
js fiddle [link]http://jsfiddle.net/mailsakthi/zL81e30z/1/ for your
perusal. Once you load the page the Plan line will not be visible and then
once you click on Previous year the Plan line will pop up. Let me know if I
can be of any further information.

**Comment by pawelfus** [comment]
Hi @sakthi 

Thank you for the example. This is caused by using only null points in the "Previous year" series with `connectNulls` option set to true.

**Comment by sakthi** [comment]
Hi Pawel,

Thank you very much for the inputs. But if I set the option to false. then
I see only markers without lines. See the image below,

[image: Inline image 1]

Kindly suggest me how to fix this issue. Thank you very much.

**Comment by PaulDalek** [comment]
I committed changes and know problem is fixed. Take a look at this corrected demo: http://jsfiddle.net/5mssLvmu/.

**Comment by sakthi** [comment]
Hi Pawel,

Thank you for the corrected demo. Can you please let know why the colors in
the legend and the actual line are not matching.

Regards,
Sakthi

**Comment by PaulDalek** [comment]
Sorry for my late reply. Symbol color is taken from the original series color (only specified segments of series are coloured). I noticed that you are using custom property `legendcolor` in your code. You can wrap `colorizeItem` function of Legend prototype to implement such option. Also, change all of `segmentcolor` into `segmentColor`.

#### Live demo
http://jsfiddle.net/g825h88a/

**Comment by sakthi** [comment]
Thank you very much for the reply.
