### ISSUE TITLE
Exception thrown since Highcharts 7.1.2

### ISSUE THREAD

**Issue by inad9300** [blacklabel/multicolor_series#27]
Since the latest Highcharts version, I started seeing the following exception in the console:

```
TypeError: p.show is not a function
    at q.applyZones (highcharts.js:349)
    at q.render (highcharts.js:352)
    at q.d (boost.js:63)
    at q.a.<computed> [as render] (highcharts.js:22)
    at eval (highcharts.js:292)
    at Array.forEach (<anonymous>)
    at a.Chart.renderSeries (highcharts.js:292)
    at a.Chart.render (highcharts.js:294)
    at a.Chart.firstRender (highcharts.js:297)
    at a.Chart.eval (highcharts.js:271)
```

I have reported the issue to Highcharts, but your plugin seems to be playing a role, so I would like to make you aware of it in case there is anything you can do.

For details, please refer to https://github.com/highcharts/highcharts/issues/11369.

Thank you!

**Comment by matixmatix** [comment]
Having the same issue.

**Comment by inad9300** [comment]
Just to clarify, there is a *workaround* in the thread above, not a solution.

**Comment by kukoba** [comment]
This workaround does not work correctly, unfortunately. Here is an example: https://jsfiddle.net/kukoba/yhL4vrkn/11/

If you will hide both series then some "phantom" series will be shown. In my project this "phantom" series shown after panning the graph to the left or to the right. 

Seems that this issue could be reproduced only if we have more then one series.

Does somebody have any idea what part of HC I should check for to fix it?

**Comment by pawelfus** [comment]
Improved workaround: https://jsfiddle.net/BlackLabel/j57e8r9k/ - change `subGraph.show();` -> `subGraph.show(true);`

**Comment by magistr4815** [comment]
Hey. I tried your fixes, but nothing worked fine.
I found a new standard charting functionality.
[Look here - zones](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/color-zones-simple/)

**Comment by magistr4815** [comment]
@kukoba None of the suggested tips on the version of "highcharts" work for me: "^ 8.1.2".
Do I understand correctly that there is no normal way to draw colored lines in segments?

**Comment by pawelfus** [comment]
FYI @PaulDalek

**Comment by magistr4815** [comment]
I found a more convenient solution! - **zones**
[Life LOOK here](https://codepen.io/magistr4815/pen/dyGOOoV)

**Comment by PaulDalek** [comment]
Hi @magistr4815

Could you provide me with an example that uses the multicolor series module where error/unintended behavior occurs even after applying all previously mentioned workarounds?
