### ISSUE TITLE
Not compatible with Highcharts v8.1.2

### ISSUE THREAD

**Issue by geekboy0801** [blacklabel/multicolor_series#29]
This is a very useful plugin,  so we've been using it in our project (React), but looks like it's not compatible with new highchart version(8.1.2).

code link:
https://codesandbox.io/s/ecstatic-engelbart-fnj7j?file=/src/App.js

screenshot:
![8 1](https://user-images.githubusercontent.com/40581883/87804821-fd5b1880-c886-11ea-81f0-2d5ade48be47.PNG)

**Comment by geekboy0801** [comment]
When I import the package(**v2.2.7**) directly from the github repo, it worked.  😊

**Comment by pawelfus** [comment]
Thanks for reporting! @PaulDalek - could you check it? It seems v2.2.7 was never released on npm?

**Comment by PaulDalek** [comment]
@geekboy0801 The newest version is already published on npm, so you can use the package from there as well.

**Comment by geekboy0801** [comment]
Thanks, @PaulDalek @pawelfus 👍
