### ISSUE TITLE
Less than two points in a series

### ISSUE THREAD

**Issue by user859** [blacklabel/multicolor_series#3]
When series consists of less than two points, exception (Cannot read property 'length' of undefined]) is thrown.

**Comment by pawelfus** [comment]
And demo: http://jsfiddle.net/av87r7uo/120/

Have you considered using `series.zones` instead of this plugin? See [API](http://api.highcharts.com/highcharts#plotOptions.series.zones).

**Comment by user859** [comment]
Yes, I have, but I cannot use a zone for whole series. I need to specify boundary value for each point separately.
