### ISSUE TITLE
spline versions of colored area and colored line 

### ISSUE THREAD

**Issue by jbkunst** [blacklabel/multicolor_series#32]
Hi everyone!

Thanks for this pluging.

How difficult is to extend this plugin to the spline versions of the current supported types?

**Comment by pawelfus** [comment]
Hi @jbkunst 

Plugin is creating separate connections between points according to the config. It's easy to create SVG path between A-B points, but Bezier lines are a bit more complicated. This is the same issue when creating spline series with null points, for example: https://jsfiddle.net/BlackLabel/jd8hvrn9/ - path is no different from basic line series.

At this moment, we don't have plans to support spline/areaspline/areasplinerange series.

Right now, we encourage using `zones`: https://jsfiddle.net/BlackLabel/bLzvdf3w/

**Comment by jbkunst** [comment]
Thanks so much @pawelfus for this clarification 😉!
