### ISSUE TITLE
Unable to load module with latest version of Highcharts

### ISSUE THREAD

**Issue by joshpitkin** [blacklabel/multicolor_series#36]
The following error is thrown on initialization:

Uncaught TypeError: Cannot read properties of undefined (reading 'drawRectangle')

Coming from this line in the module:

https://github.com/blacklabel/multicolor_series/blob/master/js/multicolor_series.js#L657

It seems that LegendSymbolMixin is deprecated or removed in the latest version of Highcharts?  I am using 9.2.2

Is this line still needed?

**Comment by totszwai** [comment]
Getting
> Uncaught TypeError: Cannot read properties of undefined (reading 'drawRectangle')
