### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by Chengminshu** [blacklabel/multicolor_series#37]
Now multicolor_ The way of reference before the series update is incompatible. How should I write it

This way of writing is wrong
import multicolor from 'highcharts-multicolor-series';
multicolor(ReactHighcharts.Highcharts);

**Comment by Chengminshu** [comment]
![image](https://user-images.githubusercontent.com/54847848/156517896-eb4dfcc0-7a16-4977-a5a6-95c7dc7b5528.png)
Now the latest version has reported an error

**Comment by zaidaldabbagh** [comment]
@Chengminshu did you manage to find a workaround for this?

**Comment by zaidaldabbagh** [comment]
@Chengminshu, I managed to resolve this with a `setTimeout`:
```
import Highcharts from 'highcharts/highstock';
import * as MulticolorSeries from 'highcharts-multicolor-series';
...
// Initialise MulticolorSeries module
setTimeout(function() { MulticolorSeries(Highcharts); }, 0);
```
