### ISSUE TITLE
Issue upgrading to highcharts v10.0.0: Series don't 

### ISSUE THREAD

**Issue by jbkunst** [blacklabel/multicolor_series#38]
Hi blacklabel team! 

I find some issues when I upgrade the highcharts version to v10.0.0. The same code worked without no problems using highcharts 8.x.x and 9.x.x

The series at the beginning is not displayed showing the next message in browser console (tested in chome and edge):

![image](https://user-images.githubusercontent.com/56481/158176333-5bdaaf7d-b865-44e1-a0f3-ae5902d902da.png)

![image](https://user-images.githubusercontent.com/56481/158176463-e2b4677c-d351-4977-977a-4a44b6ac2fb0.png)

Then, if the windows or container is resized the series is displayed:

1. At the start:
![image](https://user-images.githubusercontent.com/56481/158176600-b1396fe8-21a6-40e2-b8a3-d779b8a33248.png)

2. After resize browser window

![image](https://user-images.githubusercontent.com/56481/158176713-ca241e69-30f4-43ac-91f1-cd323979564d.png)

Thanks so much in advance.

**Comment by pawelfus** [comment]
Thank you!
The issue should be fixed with v2.4.0 release
