### ISSUE TITLE
 Can't resolve 'multicolor_series'

### ISSUE THREAD

**Issue by dineshnirali** [blacklabel/multicolor_series#39]
Hi Team,

Am using angular 15 .
    "highcharts": "^10.3.3",
    "highcharts-angular": "^3.1.2",
    "highcharts-multicolor-series": "^2.4.0",

i am getting  this error while prod build  Error: Module not found: Error: Can't resolve 'multicolor_series'

how to fix this?

**Comment by zaidaldabbagh** [comment]
@dineshnirali, I also hading the module ... I got it to work with a `setTimeout`:
```
import Highcharts from 'highcharts/highstock';
import * as MulticolorSeries from 'highcharts-multicolor-series';
...
// Initialise MulticolorSeries module
setTimeout(function() { MulticolorSeries(Highcharts); }, 0);
```
