### ISSUE TITLE
Tooltip not working

### ISSUE THREAD

**Issue by anirudh54** [blacklabel/multicolor_series#8]
the tooltips are not seen after plugin integration. narrowed down the issue to type="coloredline". If i change the type ='line'. The tooltip is working

**Comment by pawelfus** [comment]
Could you setup jsFiddle demo with that issue? It looks fine in our demos: http://www.highcharts.com/plugin-registry/single/33/Multicolor%20series

**Comment by pawelfus** [comment]
Closing as we assume it works fine. Please, reopen issue (with jsFiddle demo of the issue) if you will be able to recreate issue. Thanks!
